declare const styles: {
  readonly "addGlyph": string;
  readonly "addRow": string;
  readonly "base": string;
  readonly "chevron": string;
  readonly "chip": string;
  readonly "chips": string;
  readonly "clear": string;
  readonly "edge": string;
  readonly "edgeLine": string;
  readonly "empty": string;
  readonly "group": string;
  readonly "groupLabel": string;
  readonly "icon": string;
  readonly "input": string;
  readonly "item": string;
  readonly "itemIndicator": string;
  readonly "itemText": string;
  readonly "list": string;
  readonly "match": string;
  readonly "multiple": string;
  readonly "plate": string;
  readonly "popup": string;
  readonly "positioner": string;
  readonly "separator": string;
  readonly "status": string;
  readonly "statusError": string;
  readonly "statusGlyph": string;
  readonly "trigger": string;
};
export = styles;

