// Generated by scripts/build-colors.js. Do not edit.
import styles from './scales.module.css'

/** The 31 standard Radix scale names (§1.5.2). Alpha and custom scales are type errors [D114]. */
export const radixScales = [
  'amber',
  'blue',
  'bronze',
  'brown',
  'crimson',
  'cyan',
  'gold',
  'grass',
  'gray',
  'green',
  'indigo',
  'iris',
  'jade',
  'lime',
  'mauve',
  'mint',
  'olive',
  'orange',
  'pink',
  'plum',
  'purple',
  'red',
  'ruby',
  'sage',
  'sand',
  'sky',
  'slate',
  'teal',
  'tomato',
  'violet',
  'yellow',
] as const

export type RadixScale = (typeof radixScales)[number]

/**
 * The primary roster (§1.5.2): scales whose step 9 reaches 3:1, step 11
 * 4.5:1 and step 12 7:1 on paper and white. Greens, yellows, oranges, blue,
 * sky and cyan are secondary-only.
 */
export const primaryScales = [
  'olive',
  'sage',
  'slate',
  'sand',
  'gray',
  'mauve',
  'brown',
  'bronze',
  'gold',
  'red',
  'ruby',
  'crimson',
  'tomato',
  'pink',
  'plum',
  'indigo',
  'iris',
  'violet',
  'purple',
] as const

export type PrimaryScale = (typeof primaryScales)[number]

/** Spread into a CVA `primary` axis. Never put the axis in defaultVariants [D133]. */
export const primaryScaleVariants: Record<PrimaryScale, string> = {
  olive: styles.primaryOlive,
  sage: styles.primarySage,
  slate: styles.primarySlate,
  sand: styles.primarySand,
  gray: styles.primaryGray,
  mauve: styles.primaryMauve,
  brown: styles.primaryBrown,
  bronze: styles.primaryBronze,
  gold: styles.primaryGold,
  red: styles.primaryRed,
  ruby: styles.primaryRuby,
  crimson: styles.primaryCrimson,
  tomato: styles.primaryTomato,
  pink: styles.primaryPink,
  plum: styles.primaryPlum,
  indigo: styles.primaryIndigo,
  iris: styles.primaryIris,
  violet: styles.primaryViolet,
  purple: styles.primaryPurple,
}

/** Spread into a CVA `secondary` axis. Never put the axis in defaultVariants [D133]. */
export const secondaryScaleVariants: Record<RadixScale, string> = {
  amber: styles.secondaryAmber,
  blue: styles.secondaryBlue,
  bronze: styles.secondaryBronze,
  brown: styles.secondaryBrown,
  crimson: styles.secondaryCrimson,
  cyan: styles.secondaryCyan,
  gold: styles.secondaryGold,
  grass: styles.secondaryGrass,
  gray: styles.secondaryGray,
  green: styles.secondaryGreen,
  indigo: styles.secondaryIndigo,
  iris: styles.secondaryIris,
  jade: styles.secondaryJade,
  lime: styles.secondaryLime,
  mauve: styles.secondaryMauve,
  mint: styles.secondaryMint,
  olive: styles.secondaryOlive,
  orange: styles.secondaryOrange,
  pink: styles.secondaryPink,
  plum: styles.secondaryPlum,
  purple: styles.secondaryPurple,
  red: styles.secondaryRed,
  ruby: styles.secondaryRuby,
  sage: styles.secondarySage,
  sand: styles.secondarySand,
  sky: styles.secondarySky,
  slate: styles.secondarySlate,
  teal: styles.secondaryTeal,
  tomato: styles.secondaryTomato,
  violet: styles.secondaryViolet,
  yellow: styles.secondaryYellow,
}

/**
 * A scope's action scale (§1.11.5): Ground, and the overlay roots that
 * declare their own `white` scope, so a popup never inherits the root's.
 */
export const actionScaleVariants: Record<RadixScale, string> = {
  amber: styles.actionAmber,
  blue: styles.actionBlue,
  bronze: styles.actionBronze,
  brown: styles.actionBrown,
  crimson: styles.actionCrimson,
  cyan: styles.actionCyan,
  gold: styles.actionGold,
  grass: styles.actionGrass,
  gray: styles.actionGray,
  green: styles.actionGreen,
  indigo: styles.actionIndigo,
  iris: styles.actionIris,
  jade: styles.actionJade,
  lime: styles.actionLime,
  mauve: styles.actionMauve,
  mint: styles.actionMint,
  olive: styles.actionOlive,
  orange: styles.actionOrange,
  pink: styles.actionPink,
  plum: styles.actionPlum,
  purple: styles.actionPurple,
  red: styles.actionRed,
  ruby: styles.actionRuby,
  sage: styles.actionSage,
  sand: styles.actionSand,
  sky: styles.actionSky,
  slate: styles.actionSlate,
  teal: styles.actionTeal,
  tomato: styles.actionTomato,
  violet: styles.actionViolet,
  yellow: styles.actionYellow,
}
