// Generates the Radix color layer (§1.11.9, §1.11.2, §1.4.7):
//
// - src/utils/colors/<scale>.css, <scale>LightDefault.css, <scale>DarkDefault.css
// - src/utils/colors.css, colorsLightDefault.css, colorsDarkDefault.css
//   one unified `--{scale}{step}` set per mode, P3 values nested under
//   `color-gamut: p3`, no alpha, plus the per-scale contrast ink
//   `--{scale}-contrast` and the per-scale hover step `--{scale}-hover`
//   [D181], wrapped in the selectors of each mode strategy
// - src/utils/scales.module.css: primary<Scale> / secondary<Scale> /
//   action<Scale> classes in `@layer scales`; each secondary class also
//   publishes `--secondary-light-mark` (§1.4.7, §9.5)
// - src/utils/scales.ts: the typed CVA variant maps and scale types
import { fileURLToPath } from 'url'
import path from 'path'
import fs from 'fs'
import allColorScales from '@radix-ui/colors'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const outputDir = path.join(__dirname, '../src/utils')
const colorsDir = path.join(outputDir, 'colors')
fs.mkdirSync(colorsDir, { recursive: true })

const LIGHT = '[data-theme="light"]'
const DARK = '[data-theme="dark"]'
const OS_DARK = '@media only screen and (prefers-color-scheme: dark)'
const P3 = '@media (color-gamut: p3)'
const HEADER = '/* Generated by scripts/build-colors.js. Do not edit. */\n'

// The 31 standard scales (§1.5.2). Alpha, black and white scales are banned
// [D112] and never emitted.
const scales = {}
for (const [key, values] of Object.entries(allColorScales)) {
  if (/A$/.test(key) || typeof values !== 'object') continue
  const isDark = /Dark(P3)?$/.test(key)
  const isP3 = /P3$/.test(key)
  const name = key.replace(/(Dark)?(P3)?$/, '')
  scales[name] ??= {}
  const slot = isDark ? (isP3 ? 'darkP3' : 'dark') : isP3 ? 'lightP3' : 'light'
  scales[name][slot] = Object.values(values)
}
const scaleNames = Object.keys(scales).sort()
if (scaleNames.length !== 31) {
  throw new Error(`Expected 31 Radix scales, found ${scaleNames.length}`)
}

// Primary roster (§1.5.2): step 9 ≥ 3:1, 11 ≥ 4.5:1, 12 ≥ 7:1 on paper and white.
const primaryRoster = [
  'olive',
  'sage',
  'slate',
  'sand',
  'gray',
  'mauve',
  'brown',
  'bronze',
  'gold',
  'red',
  'ruby',
  'crimson',
  'tomato',
  'pink',
  'plum',
  'indigo',
  'iris',
  'violet',
  'purple',
]
for (const s of primaryRoster) {
  if (!scales[s]) throw new Error(`Unknown primary scale ${s}`)
}

// ---------------------------------------------------------------------------
// WCAG 2 contrast (§1.4.7)

function luminance(hex) {
  const h = hex.replace('#', '')
  const full =
    h.length === 3
      ? h
          .split('')
          .map((c) => c + c)
          .join('')
      : h.slice(0, 6)
  const [r, g, b] = [0, 2, 4].map((i) => {
    const c = parseInt(full.slice(i, i + 2), 16) / 255
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

function contrast(a, b) {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (l1 + 0.05) / (l2 + 0.05)
}

/**
 * The contrast ink for text and glyphs on step 9 (and 10) of a scale in one
 * mode. Candidates are the scale's own darkest and lightest step for that
 * mode; white only in dark mode, and only when neither own step reaches
 * 4.5:1. The highest-contrast candidate wins, so "none" scales still get a
 * glyph-safe (≥ 3:1) value.
 */
function contrastInk(name, mode) {
  const steps = scales[name][mode]
  const step9 = steps[8]
  const candidates = [
    { value: `var(--${name}1)`, ratio: contrast(steps[0], step9) },
    { value: `var(--${name}12)`, ratio: contrast(steps[11], step9) },
  ]
  if (mode === 'dark' && candidates.every((c) => c.ratio < 4.5)) {
    candidates.push({ value: '#fff', ratio: contrast('#ffffff', step9) })
  }
  candidates.sort((a, b) => b.ratio - a.ratio)
  return candidates[0]
}

// ---------------------------------------------------------------------------
// Hover step (§1.4.3 step-role table, §1.5.3 hover table) [D181]

/*
 * Scales whose light-scope label is their own step 1: the lighter
 * neighbour would drop that label below target, so their hover takes
 * step 10 in a light scope too.
 */
const hoverStep10Light = new Set(['purple', 'indigo', 'iris', 'violet', 'plum'])

/**
 * The step a contained fill moves to on hover: the rest fill's (step 9)
 * lighter Radix neighbour in a light scope, and step 10 in a dark scope.
 * The lighter neighbour is the highest step below 9 that is lighter than
 * step 9: step 8 for most scales, amber 6 and yellow 5 (and lime, mint and
 * sky 5), whose steps 6–8 are darker than their bright step 9.
 *
 * In a dark scope, where step 10 would drop the scale's contrast ink below
 * 4.5:1 (the white-ink scales: gray, indigo, iris, mauve, olive, plum,
 * purple, sage, sand, slate, violet at 4.05–4.40), the hover takes the
 * other neighbour, step 8 (5.29–6.29), as the light step-10 rule does
 * (derived; flagged for user review, §1.8).
 */
function hoverStep(name, mode) {
  if (mode === 'dark') {
    const steps = scales[name].dark
    const ink = contrastInk(name, 'dark').value
    const inkHex = ink === '#fff' ? '#ffffff' : ink.includes(`${name}1)`) ? steps[0] : steps[11]
    return contrast(inkHex, steps[9]) >= 4.5 ? 10 : 8
  }
  if (hoverStep10Light.has(name)) return 10
  const steps = scales[name].light
  const l9 = luminance(steps[8])
  for (let i = 7; i >= 0; i--) {
    if (luminance(steps[i]) > l9) return i + 1
  }
  return 10
}

// ---------------------------------------------------------------------------
// CSS blocks

function declarations(names, mode, indent) {
  const pad = ' '.repeat(indent)
  const lines = []
  const p3Lines = []
  for (const name of names) {
    const s = scales[name]
    s[mode].forEach((v, i) => lines.push(`${pad}--${name}${i + 1}: ${v};`))
    lines.push(`${pad}--${name}-contrast: ${contrastInk(name, mode).value};`)
    lines.push(`${pad}--${name}-hover: var(--${name}${hoverStep(name, mode)});`)
    s[`${mode}P3`]?.forEach((v, i) =>
      p3Lines.push(`${pad}  --${name}${i + 1}: ${v};`)
    )
  }
  return `${lines.join('\n')}\n\n${pad}${P3} {\n${p3Lines.join('\n')}\n${pad}}`
}

function block(selector, body, indent = 0) {
  const pad = ' '.repeat(indent)
  return `${pad}${selector} {\n${body}\n${pad}}`
}

/**
 * strategy: 'follow' (default), 'light' (light-default) or 'dark' (dark-default).
 * In every strategy the attribute-only block follows the `:root` block, so
 * `data-theme` wins at equal specificity.
 */
function generate(names, strategy) {
  const light = (indent) => declarations(names, 'light', indent)
  const dark = (indent) => declarations(names, 'dark', indent)
  const parts = []
  if (strategy === 'dark') {
    parts.push(block(`:root,\n  ${DARK}`, dark(4), 2))
    parts.push(block(LIGHT, light(4), 2))
    // Print always renders light (§1.11.6).
    parts.push(block('@media print', block(':root', light(6), 4), 2))
  } else {
    parts.push(block(`:root,\n  ${LIGHT}`, light(4), 2))
    parts.push(block(DARK, dark(4), 2))
    if (strategy === 'follow') {
      parts.push(block(OS_DARK, block(`:root:not(${LIGHT})`, dark(6), 4), 2))
    }
  }
  return `${HEADER}@layer theme {\n${parts.join('\n\n')}\n}\n`
}

const variants = [
  ['', 'follow'],
  ['LightDefault', 'light'],
  ['DarkDefault', 'dark'],
]

const report = []
for (const name of scaleNames) {
  for (const [suffix, strategy] of variants) {
    fs.writeFileSync(
      path.join(colorsDir, `${name}${suffix}.css`),
      generate([name], strategy)
    )
  }
  const l = contrastInk(name, 'light')
  const d = contrastInk(name, 'dark')
  report.push(
    `${name.padEnd(8)} light ${l.value.padEnd(16)} ${l.ratio.toFixed(2)}   dark ${d.value.padEnd(16)} ${d.ratio.toFixed(2)}   hover ${hoverStep(name, 'light')} / ${hoverStep(name, 'dark')}`
  )
}
for (const [suffix, strategy] of variants) {
  fs.writeFileSync(
    path.join(outputDir, `colors${suffix}.css`),
    generate(scaleNames, strategy)
  )
}

// ---------------------------------------------------------------------------
// scales.module.css and scales.ts (§1.11.2)

const pascal = (s) => s[0].toUpperCase() + s.slice(1)

/*
 * The light-scope mark on a secondary step 9 (§1.4.7): the scale's own
 * contrast ink where it carries text there (≥ 4.5:1: amber, gray, indigo,
 * iris, lime, mauve, mint, olive, plum, purple, sage, sand, sky, slate,
 * violet, yellow); otherwise `initial`, so the light role maps fall back to
 * the primary's step 12 (P12*, the text ink for blue, bronze, brown, cyan,
 * grass, green, jade, orange and teal; the glyph ink for the six "none"
 * scales, which carry no words on step 9). Every secondary class declares
 * it, so an override never inherits its scope's value.
 */
function lightMark(name) {
  return contrastInk(name, 'light').ratio >= 4.5 ? 'var(--secondary-contrast)' : 'initial'
}

function scaleClass(slot, name) {
  const lines = []
  for (let i = 1; i <= 12; i++) {
    lines.push(`    --${slot}${i}: var(--${name}${i});`)
  }
  lines.push(`    --${slot}-contrast: var(--${name}-contrast);`)
  lines.push(`    --${slot}-hover: var(--${name}-hover);`)
  if (slot === 'secondary') lines.push(`    --secondary-light-mark: ${lightMark(name)};`)
  return `  .${slot}${pascal(name)} {\n${lines.join('\n')}\n  }`
}

const moduleCss = `${HEADER}/*
 * One class per scale per slot (§1.11.2). The scales layer sits above base,
 * variants and compounds, so an explicit color prop beats any fallback.
 * No mode logic: the Radix variables resolve to whatever mode is in effect.
 * action<Scale> publishes a scope's action scale: Ground, and the overlay
 * roots that declare their own scope, so a popup never inherits the root's.
 * --secondary-light-mark: the light-scope mark on step 9, the scale's own
 * contrast ink where it carries text, else \`initial\` so the role maps fall
 * back to --primary12 (§1.4.7).
 */
@layer scales {
${['primary', 'secondary', 'action']
  .flatMap((slot) => scaleNames.map((n) => scaleClass(slot, n)))
  .join('\n\n')}
}
`
fs.writeFileSync(path.join(outputDir, 'scales.module.css'), moduleCss)

const q = (s) => `'${s}'`
const map = (slot, names) =>
  names.map((n) => `  ${n}: styles.${slot}${pascal(n)},`).join('\n')

const scalesTs = `// Generated by scripts/build-colors.js. Do not edit.
import styles from './scales.module.css'

/** The 31 standard Radix scale names (§1.5.2). Alpha and custom scales are type errors [D114]. */
export const radixScales = [
${scaleNames.map((n) => `  ${q(n)},`).join('\n')}
] as const

export type RadixScale = (typeof radixScales)[number]

/**
 * The primary roster (§1.5.2): scales whose step 9 reaches 3:1, step 11
 * 4.5:1 and step 12 7:1 on paper and white. Greens, yellows, oranges, blue,
 * sky and cyan are secondary-only.
 */
export const primaryScales = [
${primaryRoster.map((n) => `  ${q(n)},`).join('\n')}
] as const

export type PrimaryScale = (typeof primaryScales)[number]

/** Spread into a CVA \`primary\` axis. Never put the axis in defaultVariants [D133]. */
export const primaryScaleVariants: Record<PrimaryScale, string> = {
${map('primary', primaryRoster)}
}

/** Spread into a CVA \`secondary\` axis. Never put the axis in defaultVariants [D133]. */
export const secondaryScaleVariants: Record<RadixScale, string> = {
${map('secondary', scaleNames)}
}

/**
 * A scope's action scale (§1.11.5): Ground, and the overlay roots that
 * declare their own \`white\` scope, so a popup never inherits the root's.
 */
export const actionScaleVariants: Record<RadixScale, string> = {
${map('action', scaleNames)}
}
`
fs.writeFileSync(path.join(outputDir, 'scales.ts'), scalesTs)

if (process.env.DEBUG_CONTRAST) console.log(report.join('\n'))
