/** A long page: the seed-saving guide's sections, so the bar's panel scrolls and centers. */
export const guide: { id: string; title: string; level: 2 | 3; body: string }[] = [
  { id: 'bar-why-save-seed', title: 'Why save seed', level: 2, body: 'Seed saved from the plants that did best in our beds grows better in them next year, and it keeps the library shelves full.' },
  { id: 'bar-choosing-plants', title: 'Choosing plants', level: 2, body: 'Save from the healthiest plants, never from the first to bolt or the last to ripen.' },
  { id: 'bar-open-pollinated', title: 'Open-pollinated varieties', level: 3, body: 'Hybrids don’t come true from seed; the library’s packets say which varieties are open-pollinated.' },
  { id: 'bar-keeping-apart', title: 'Keeping varieties apart', level: 3, body: 'Squash and corn cross with their neighbours; grow one variety a season, or bag the flowers.' },
  { id: 'bar-tomatoes', title: 'Tomatoes', level: 2, body: 'Tomatoes are the easiest start: every fruit holds a hundred seeds.' },
  { id: 'bar-picking-fruit', title: 'Picking the fruit', level: 3, body: 'Pick one fully ripe fruit from each of three plants.' },
  { id: 'bar-fermenting', title: 'Fermenting the seed', level: 3, body: 'Squeeze the seed and pulp into a jar with a little water and leave it three days, stirring daily.' },
  { id: 'bar-drying-tomato', title: 'Drying', level: 3, body: 'Rinse the seed that sank, spread it on a plate and dry it for a week out of the sun.' },
  { id: 'bar-beans-and-peas', title: 'Beans and peas', level: 2, body: 'Beans and peas pollinate themselves, so any row will do.' },
  { id: 'bar-pods-on-vine', title: 'Leaving pods on the vine', level: 3, body: 'Leave a few plants unpicked until the pods rattle.' },
  { id: 'bar-threshing', title: 'Threshing', level: 3, body: 'Shell the pods over a sheet, or tread them in a pillowcase and winnow the chaff in a breeze.' },
  { id: 'bar-lettuce', title: 'Lettuce', level: 2, body: 'Lettuce seed comes late in the summer from plants left to flower.' },
  { id: 'bar-letting-bolt', title: 'Letting it bolt', level: 3, body: 'Mark two good plants in spring and let them grow tall; stake them before the flowers open.' },
  { id: 'bar-shaking-heads', title: 'Shaking the heads', level: 3, body: 'When the fluffy heads appear, shake them into a paper bag every few days.' },
  { id: 'bar-squash', title: 'Squash', level: 2, body: 'Squash needs the most care: it crosses easily and its seed must ripen inside the fruit.' },
  { id: 'bar-hand-pollinating', title: 'Hand pollinating', level: 3, body: 'Tape a female flower shut the evening before it opens, then dust it with a male flower of the same variety.' },
  { id: 'bar-scooping', title: 'Scooping and washing', level: 3, body: 'Leave the fruit a month after harvest, then scoop, wash and dry the plump seed.' },
  { id: 'bar-storing-seed', title: 'Storing seed', level: 2, body: 'Dry seed keeps for years in the cool and dark.' },
  { id: 'bar-envelopes', title: 'Envelopes and labels', level: 3, body: 'Write the variety, the plot and the year on the envelope before the seed goes in.' },
  { id: 'bar-library-shelves', title: 'The seed library shelves', level: 3, body: 'Return a share to the library tin in the tool shed; the coordinators sort it each month.' },
  { id: 'bar-sharing', title: 'Sharing', level: 2, body: 'Everything saved goes round again in spring.' },
  { id: 'bar-spring-swap', title: 'The spring swap', level: 3, body: 'Bring your envelopes to the March work day and leave with someone else’s.' },
]
